### ISSUE TITLE
Farm's Roadmap - 2023

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#7]
Farm aims to provide basic performant compilation support(React tech stack) for web project this year(2022), releasing a stable version which can be used in production.

##  Project Infrastructure
**CI for testing, linting, coverage report, auto release and so on**
   - [x] Support node bindings and cross platform tests
   - [x] Cross-platform building and artifact upload
   - [x] Release packages using changesets 
   - [ ] Gathering rust and ts test coverage and report them as single one

**Test spec for rust and ts**
- [x] Shared rust test utilities for the input file/output file diff integration test
- [x] Shared ts test for input file/executing result diff integration test
- [x] Utilities for rust plugins test
- [x] Utilities for js plugins test

**Project Management**
- [x] contribution guide
- [x] issue and pr templates

## Farm Core Design
- [x] Farm Architecture #3 
   - [x] Plugin system support both js plugin and rust plugin
       - [x] Well designed plugin hook for the entire compilation flow
       - [x] Js plugins with filtering support
       - [x] rust plugin loading and executing
   - [x] Well designed core data structure like Module, ModuleGroup, ModuleGraph and so on
   - [x] Well designed error handling like rust, give the specific cause and the detailed suggested solution
- [x] Runtime module system for Browser and Node #9 
- [x] Well designed module merging algorithm, with lock for consistency support
- [x] Well designed universal cache system
- [x] Well designed HMR interface
- [x] Well designed core data structure support all web assets as first class citizen
- [x] Well designed tree shaking algorithm

 ## Features
**Script(`js, ts, jsx, tsx`) compilation**
- [x] Resolving, parsing, minimizing, code generation and dependencies analyzing for all four script types, `jsx/tsx` support react by default
- [x] Strip type for `ts/tsx` (without type checking)
- [x] Polyfill, syntax downgrade and api inject
- [x] Tree-shaking
- [x] Sourcemap
- [x] Native support swc plugins

**Css(`sass, less, css`) compilation**
- [x] Resolving, parsing, minimizing, code generation and dependencies analyzing for all three css types
- [x] Css modules support
- [x] Sourcemap
- [ ] Native HMR support for link tag and style tag

**Html compilation**
- [x] Native support resolving, parsing, minimizing, code generation and dependencies analyzing(script, link tag) for html
- [ ] Prefetch and preload

**React compilation**
- [x] React refresh

**SSR**
- [x] Executable ESM production for node.js
- [x] Native react ssr support

**Optimization**
- [x] Lazy compilation
- [x] Module merging
    - [x] Internal well designed module merging algorithm
    - [x] Custom module merging strategy by config

## Ecosystem
- [x] Official React project templates and CLI tools
- [x] Official website and documents

**Comment by wre232114** [comment]
cc @farm-fe/admin

**Comment by whatreal** [comment]
`emitDecoratorMetadata` support?

**Comment by wre232114** [comment]
Not support for now. But it can be implemented quickly based on swc

**Comment by whatreal** [comment]
so，where is swc plugin?

**Comment by wre232114** [comment]
see https://farm-fe.github.io/docs/config/farm-config#scriptplugins
